CREATE TABLE PAIS (
	CODIGO_PA serial NOT NULL,
	NOMBRE_PA varchar(100) NOT NULL,
	ESTADO_PA varchar(1) NOT NULL,
	USUARIO_ACT_PA integer NOT NULL,
	FECHA_ACT_PA DATE NOT NULL,
	CONSTRAINT PAIS_pk PRIMARY KEY (CODIGO_PA)
) WITH (
  OIDS=FALSE
);



CREATE TABLE CIUDAD (
	CODIGO_CI serial NOT NULL,
	NOMBRE_CI varchar(100) NOT NULL,
	ESTADO_CI varchar(1) NOT NULL,
	USUARIO_ACT_CI integer NOT NULL,
	FECHA_ACT_CI DATE NOT NULL,
	PAIS integer NOT NULL,
	CONSTRAINT CIUDAD_pk PRIMARY KEY (CODIGO_CI)
) WITH (
  OIDS=FALSE
);



CREATE TABLE AEREOPUERTO (
	CODIGO_AE serial NOT NULL,
	NOMBRE_AE varchar(500) NOT NULL,
	ESTADO_AE varchar(1) NOT NULL,
	USUARIO_ACT_AE integer NOT NULL,
	FECHA_ACT_AE DATE NOT NULL,
	CIUDAD integer NOT NULL,
	CONSTRAINT AEREOPUERTO_pk PRIMARY KEY (CODIGO_AE)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TIPO_PASAJERO (
	CODIGO_TP serial NOT NULL,
	NOMBRE_TP varchar(100) NOT NULL,
	ESTADO_TP varchar(1) NOT NULL,
	USUARIO_ACT_TP integer NOT NULL,
	FECHA_ACT_TP DATE NOT NULL,
	CONSTRAINT TIPO_PASAJERO_pk PRIMARY KEY (CODIGO_TP)
) WITH (
  OIDS=FALSE
);



CREATE TABLE PASAJERO (
	CODIGO_PS serial NOT NULL,
	NOMBRE_PS varchar(100) NOT NULL,
	APELLIDO_PS varchar(100) NOT NULL,
	IDENTIFIACION_PS varchar(20) NOT NULL,
	CORREO_PS varchar(100) NOT NULL,
	TIPO_IDENTIFICACION integer NOT NULL,
	DIRECCION integer NOT NULL,
	ESTADO_PS varchar(1) NOT NULL,
	USUARIO_ACT_PS integer NOT NULL,
	FECHA_ACT_PS DATE NOT NULL,
	TIPO_PASAJERO integer NOT NULL,
	CONSTRAINT PASAJERO_pk PRIMARY KEY (CODIGO_PS)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TIPO_IDENTIFICACION (
	CODIGO_TI serial NOT NULL,
	NOMBRE_TI varchar(100) NOT NULL,
	ESTADO_TI varchar(1) NOT NULL,
	USUARIO_ACT_TI integer NOT NULL,
	FECHA_ACT_TI DATE NOT NULL,
	CONSTRAINT TIPO_IDENTIFICACION_pk PRIMARY KEY (CODIGO_TI)
) WITH (
  OIDS=FALSE
);



CREATE TABLE DIRECCION (
	CODIGO_DI serial NOT NULL,
	CALLE_PRINCIPAL_DI varchar(1000) NOT NULL,
	CALLE_SECUNDARIA_DI varchar(1000) NOT NULL,
	NUMERO_DI varchar(20) NOT NULL,
	CODIGO_POSTAL varchar(100) NOT NULL,
	CONSTRAINT DIRECCION_pk PRIMARY KEY (CODIGO_DI)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TIPO_CONTACTO (
	CODIGO_TC serial NOT NULL,
	NOMBRE_TC varchar(500) NOT NULL,
	ESTADO_TC varchar(1) NOT NULL,
	USUARIO_ACT_TP integer NOT NULL,
	FECHA_ACT_TP DATE NOT NULL,
	CONSTRAINT TIPO_CONTACTO_pk PRIMARY KEY (CODIGO_TC)
) WITH (
  OIDS=FALSE
);



CREATE TABLE CONTACTO_PASAJERO (
	CODIGO_CP serial NOT NULL,
	NUMERO_CP varchar(20) NOT NULL,
	ESTADO_CP varchar(1) NOT NULL,
	USUARIO_ACT_CP integer NOT NULL,
	FECHA_ACT_CP DATE NOT NULL,
	TIPO_CONTACTO integer NOT NULL,
	PASAJERO integer NOT NULL,
	CONSTRAINT CONTACTO_PASAJERO_pk PRIMARY KEY (CODIGO_CP)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TIPO_VUELO (
	CODIGO_TV serial NOT NULL,
	NOMBRE_TV varchar(100) NOT NULL,
	ESTADO_TV varchar(1) NOT NULL,
	USUARIO_ACT_TV integer NOT NULL,
	FECHA_ACT_TV DATE NOT NULL,
	CONSTRAINT TIPO_VUELO_pk PRIMARY KEY (CODIGO_TV)
) WITH (
  OIDS=FALSE
);



CREATE TABLE VUELO (
	CODIGO_VU serial NOT NULL,
	NUMERO_VU varchar(100) NOT NULL,
	FECHA_VU DATE NOT NULL,
	HORA_VU DATE NOT NULL,
	DURACION_VU FLOAT NOT NULL,
	ESTADO_VU varchar(1) NOT NULL,
	USUARIO_ACT_VU integer NOT NULL,
	FECHA_ACT_VU DATE NOT NULL,
	TIPO_ESTADO integer NOT NULL,
	TIPO_VUELO integer NOT NULL,
	AEREOPUERTO integer NOT NULL,
	AEREOLINEA integer NOT NULL,
	CONSTRAINT VUELO_pk PRIMARY KEY (CODIGO_VU)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TIPO_ESTADO (
	CODIGO_TE serial NOT NULL,
	NOMBRE_TE varchar(100) NOT NULL,
	ESTADO_TE varchar(1) NOT NULL,
	USUARIO_ACT_TE integer NOT NULL,
	FECHA_ACT_TE DATE NOT NULL,
	CONSTRAINT TIPO_ESTADO_pk PRIMARY KEY (CODIGO_TE)
) WITH (
  OIDS=FALSE
);



CREATE TABLE AEREOLINEA (
	CODIGO_AR serial NOT NULL,
	NOMBRE_AR varchar(500) NOT NULL,
	ESTADO_AR varchar(1) NOT NULL,
	USUARIO_ACT_AR integer NOT NULL,
	FECHA_ACT_AR DATE NOT NULL,
	CONSTRAINT AEREOLINEA_pk PRIMARY KEY (CODIGO_AR)
) WITH (
  OIDS=FALSE
);



CREATE TABLE RESERVA (
	CODIGO_RS serial NOT NULL,
	DESDE_RS integer NOT NULL,
	HACIA_RS integer NOT NULL,
	FECHA_SALIDA DATE NOT NULL,
	FECHA_RETORNO DATE NOT NULL,
	NUMERO_RS varchar(100) NOT NULL,
	VUELO_IDA_RS integer NOT NULL,
	VUELO_RETORNO_RS integer NOT NULL,
	ESTADO_RS varchar(1) NOT NULL,
	USUARIO_ACT_RS integer NOT NULL,
	FECHA_ACT_RS DATE NOT NULL,
	CONSTRAINT RESERVA_pk PRIMARY KEY (CODIGO_RS)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TIPO_RESERVA (
	CODIGO_TR serial NOT NULL,
	NOMBRE_TR varchar(100) NOT NULL,
	ESTADO_TR varchar(1) NOT NULL,
	USUARIO_ACT_TR integer NOT NULL,
	FECHA_ACT_TR DATE NOT NULL,
	CONSTRAINT TIPO_RESERVA_pk PRIMARY KEY (CODIGO_TR)
) WITH (
  OIDS=FALSE
);



CREATE TABLE PASAJERO_RESERVA (
	CODIGO_PR serial NOT NULL,
	PASAJERO integer NOT NULL,
	RESERVA integer NOT NULL,
	CONSTRAINT PASAJERO_RESERVA_pk PRIMARY KEY (CODIGO_PR)
) WITH (
  OIDS=FALSE
);




ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_fk0 FOREIGN KEY (PAIS) REFERENCES PAIS(CODIGO_PA);

ALTER TABLE AEREOPUERTO ADD CONSTRAINT AEREOPUERTO_fk0 FOREIGN KEY (CIUDAD) REFERENCES CIUDAD(CODIGO_CI);


ALTER TABLE PASAJERO ADD CONSTRAINT PASAJERO_fk0 FOREIGN KEY (TIPO_IDENTIFICACION) REFERENCES TIPO_IDENTIFICACION(CODIGO_TI);
ALTER TABLE PASAJERO ADD CONSTRAINT PASAJERO_fk1 FOREIGN KEY (DIRECCION) REFERENCES DIRECCION(CODIGO_DI);
ALTER TABLE PASAJERO ADD CONSTRAINT PASAJERO_fk2 FOREIGN KEY (TIPO_PASAJERO) REFERENCES TIPO_PASAJERO(CODIGO_TP);




ALTER TABLE CONTACTO_PASAJERO ADD CONSTRAINT CONTACTO_PASAJERO_fk0 FOREIGN KEY (TIPO_CONTACTO) REFERENCES TIPO_CONTACTO(CODIGO_TC);
ALTER TABLE CONTACTO_PASAJERO ADD CONSTRAINT CONTACTO_PASAJERO_fk1 FOREIGN KEY (PASAJERO) REFERENCES PASAJERO(CODIGO_PS);


ALTER TABLE VUELO ADD CONSTRAINT VUELO_fk0 FOREIGN KEY (TIPO_ESTADO) REFERENCES TIPO_ESTADO(CODIGO_TE);
ALTER TABLE VUELO ADD CONSTRAINT VUELO_fk1 FOREIGN KEY (TIPO_VUELO) REFERENCES TIPO_VUELO(CODIGO_TV);
ALTER TABLE VUELO ADD CONSTRAINT VUELO_fk2 FOREIGN KEY (AEREOPUERTO) REFERENCES AEREOPUERTO(CODIGO_AE);
ALTER TABLE VUELO ADD CONSTRAINT VUELO_fk3 FOREIGN KEY (AEREOLINEA) REFERENCES AEREOLINEA(CODIGO_AR);



ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk0 FOREIGN KEY (DESDE_RS) REFERENCES AEREOPUERTO(CODIGO_AE);
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk1 FOREIGN KEY (HACIA_RS) REFERENCES AEREOPUERTO(CODIGO_AE);
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk2 FOREIGN KEY (VUELO_IDA_RS) REFERENCES VUELO(CODIGO_VU);
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk3 FOREIGN KEY (VUELO_RETORNO_RS) REFERENCES VUELO(CODIGO_VU);


ALTER TABLE PASAJERO_RESERVA ADD CONSTRAINT PASAJERO_RESERVA_fk0 FOREIGN KEY (PASAJERO) REFERENCES PASAJERO(CODIGO_PS);
ALTER TABLE PASAJERO_RESERVA ADD CONSTRAINT PASAJERO_RESERVA_fk1 FOREIGN KEY (RESERVA) REFERENCES RESERVA(CODIGO_RS);

