ALTER TABLE RESERVA ADD TIPO_CABINA INTEGER;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk5 FOREIGN KEY (TIPO_CABINA) REFERENCES TIPO_CABINA(CODIGO_TC);

ALTER TABLE RESERVA ADD TIPO_TARIFA_IDA INTEGER;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk6 FOREIGN KEY (TIPO_TARIFA_IDA) REFERENCES TIPO_TARIFA(CODIGO_TT);

ALTER TABLE RESERVA ADD TIPO_TARIFA_REGRESO INTEGER;

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_fk7 FOREIGN KEY (TIPO_TARIFA_REGRESO) REFERENCES TIPO_TARIFA(CODIGO_TT);