CREATE TABLE CONDICIONES (
	CODIGO_CO serial NOT NULL,
	NOMBRE_CO varchar(100) NOT NULL,
	ESTADO_CO varchar(1) NOT NULL,
	USUARIO_ACT_CO integer NOT NULL,
	FECHA_ACT_CO DATE NOT NULL,
	CONSTRAINT CONDICIONES_pk PRIMARY KEY (CODIGO_CO)
) WITH (
  OIDS=FALSE
);

CREATE TABLE TARIFA_CONDICIONES (
	CODIGO_TC serial NOT NULL,
	CONDICION integer NOT NULL,
	TIPO_TARIFA integer NOT NULL,
	DESCRIPCION varchar(500) NOT NULL,
	ESTADO_TC varchar(1) NOT NULL,
	USUARIO_ACT_TC integer NOT NULL,
	FECHA_ACT_TC DATE NOT NULL,
	CONSTRAINT TARIFA_CONDICIONES_pk PRIMARY KEY (CODIGO_TC)
) WITH (
  OIDS=FALSE
);


ALTER TABLE TARIFA_CONDICIONES ADD CONSTRAINT TARIFA_CONDICIONES_fk1 FOREIGN KEY (TIPO_TARIFA) REFERENCES TIPO_TARIFA(CODIGO_TT);
ALTER TABLE TARIFA_CONDICIONES ADD CONSTRAINT TARIFA_CONDICIONES_fk2 FOREIGN KEY (CONDICION) REFERENCES CONDICIONES(CODIGO_CO);
