CREATE TABLE TIPO_IMPUESTO (
	CODIGO_TI serial NOT NULL,
	NOMBRE_TI varchar(100) NOT NULL,
	ESTADO_TI varchar(1) NOT NULL,
	USUARIO_ACT_TI integer NOT NULL,
	FECHA_ACT_TI DATE NOT NULL,
	CONSTRAINT TIPO_IMPUESTO_pk PRIMARY KEY (CODIGO_TI)
) WITH (
  OIDS=FALSE
);

CREATE TABLE IMPUESTO (
	CODIGO_IM serial NOT NULL,
	VALOR_IM integer NOT NULL,
	TIPO_IMPUESTO integer NOT NULL,
	DESCRIPCION_IM varchar(500) NOT NULL,
	NEMONICO_IM varchar(20) NOT NULL,
	ESTADO_IM varchar(1) NOT NULL,
	USUARIO_ACT_IM integer NOT NULL,
	FECHA_ACT_IM DATE NOT NULL,
	CONSTRAINT IMPUESTO_pk PRIMARY KEY (CODIGO_IM)
) WITH (
  OIDS=FALSE
);


ALTER TABLE IMPUESTO ADD CONSTRAINT IMPUESTO_fk1 FOREIGN KEY (TIPO_IMPUESTO) REFERENCES TIPO_IMPUESTO(CODIGO_TI);

ALTER TABLE TIPO_PASAJERO ADD PORCENTAJE_TARIFA_TP FLOAT;

CREATE TABLE PASAJERO_COSTO (
	CODIGO_PC serial NOT NULL,
	TARIFA_PC float,
	IMPUESTO_PC float,
	PASAJERO integer,
	RESERVA integer,
	ESTADO_PC varchar(1) NOT NULL,
	USUARIO_ACT_PC integer NOT NULL,
	FECHA_ACT_PC DATE NOT NULL,
	CONSTRAINT PASAJERO_COSTO_pk PRIMARY KEY (CODIGO_PC)
) WITH (
  OIDS=FALSE
);

ALTER TABLE PASAJERO_COSTO ADD CONSTRAINT PASAJERO_COSTO_fk1 FOREIGN KEY (PASAJERO) REFERENCES PASAJERO(CODIGO_PS);
ALTER TABLE PASAJERO_COSTO ADD CONSTRAINT PASAJERO_COSTO_fk2 FOREIGN KEY (RESERVA) REFERENCES RESERVA(CODIGO_RS);

ALTER TABLE RESERVA ADD COSTO_TOTAL_RS FLOAT;